services:
  database:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres1
      POSTGRES_DB: ecommercedb
    volumes:
      - database_data:/var/lib/postgresql/data
volumes:
  database_data: