services:
  database:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: ecommercedb
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data:
