services:
  database:
    image: postgres
    restart: always
    ports:
      -"${DB_PORT}":5432
    environment:
      POSEGRES_PASSWORD= ${DATABASE_PASSWORD}
    volumes:
      - database_data:/var/lib/postgresql/data
volumes:
  database_data: